language: java
os:
- linux
jdk: 
- oraclejdk11
env:
- PROJECT_DIR=HashTable
- PROJECT_DIR=Trie
- PROJECT_DIR=BinarySearchTree
- PROJECT_DIR=ThreadPool
- PROJECT_DIR=QSort
- PROJECT_DIR=Phonebook
- PROJECT_DIR=MyJUnit
script: cd $PROJECT_DIR && mvn install 
